assets:
  runners_video: 'assets/people_running.mp4'
  output_filename: 'assets/people_running_processed.mp4'

model:
  detection: 'models/yolov8n.pt' 

draw:
  box_color: [0, 200, 0]
  box_width: 2
  text_font: 'cv2.FONT_HERSHEY_SIMPLEX'
  text_fontsize: 0.5
  text_color: [139, 100, 0]
  text_width: 1

line:
  start: [739, 448]
  end: [546, 333]

