assets:
  input_video: 'assets/oranges.mp4'
  output_filename: 'assets/oranges_processed_sv.mp4'

model:
  detection: 'models/yolov8n.pt' 
  #detection: 'models/yolov8x.pt' 
  
  # # model = YOLO("yolov8n.pt")
  # # model = YOLO("yolov8s.pt")
  # # model = YOLO("yolov8m.pt")
  # # model = YOLO("yolov8l.pt")
  # # model = YOLO("yolov8x.pt")

line:
  x1: 500
  y1: 1750
  x2: 3000
  y2: 1750
  color: sv.Color(255, 150, 150)
  text_in: 'in'
  text_out: 'out'
  text_scale: 0.5
  thickness: 2
  text_thickness: 1

